name: Update HTML on Commit

on: [push]

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update HTML file
      run: |
        echo "Updated on $(date) >> index.html"

    - name: Commit changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'matheus kenzo'
        git config --global user.email 'kenzoyamashitaasano@gmail.com'
        git add index.html
        git commit -m "Update index.html on commit"
        # git push https://${{ secrets.GH_PAT }}@github.com/matheuskya/devops_aula.git HEAD:main
        git push origin main
