name: Update HTML on Commit

on: [push]

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update HTML file
      run: |
        echo "<!-- Updated on $(date) -->" >> main.html

    - name: Commit changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add main.html
        git commit -m "Update main.html on commit"
        # git push https://${{ secrets.GH_PAT }}@github.com/matheuskya/devops_aula.git HEAD:main
        git push origin main
